export const initialState = {
  steps: [
    { id: 0, label: "Логин и пароль" },
    { id: 1, label: "Где проживаете?" },
    { id: 2, label: "Номер телефона" },
  ],
  fields: [
    {
      id:0,
      label: "Введите логин",
      name: "login",
      stepId: 0,
      required: true,
    },
    {
      id:1,
      label: "Введите почту",
      name: "email",
      type: "email",
      stepId: 0,
      required: true,
    },
    {
      id:2,
      label: "Введите пароль",
      name: "password",
      type: "password",
      stepId: 0,
      required: true,
    },
    {
      id:3,
      label: "Повторите пароль",
      name: "repeatPassword",
      type: "password",
      stepId: 0,
      required: true,
    },
    {
      id:4,
      label: "Страна",
      name: "country",
      stepId: 1,
      required: true,
    },
    {

      id:5,
      label: "Город",
      name: "city",
      stepId: 1,
      required: true,
    },
    {
      id:6,
      label: "Улица",
      name: "street",
      stepId: 1,
      required: false,
    },
    {

      id:7,
      label: "Дом",
      name: "house",
      stepId: 1,
      required: false,
    },
    {
      id:8,
      label: "Номер телефона",
      name: "phone",
      type: "number",
      send:true,
      stepId: 2,
      required: true,
    },
    {
      id:9,
      label: "Введите код",
      name: "code",
      stepId: 2,
      required: true,
    },
  ],
};
